version: "3.8"

services:
  orders-service:
    image: monapp-orders-service:latest
    container_name: orders-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - spring_profiles_active=dev
    depends_on:
      - mongodb
    networks:
      - monitoring-net

  mongodb:
    image: mongo:6
    container_name: orders-db
    ports:
      - "27017:27017"
    networks:
      - monitoring-net
    volumes:
      - mongo-data:/data/db

  dredd:
    image: node:20
    depends_on:
      - orders-service
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "
        npm install -g dredd &&
        curl http://orders-service:8080/v3/api-docs -o swagger.json &&
        dredd swagger.json http://orders-service:8080 --hookfiles=hooks.js
      "

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
    depends_on:
      - prometheus

networks:
  monitoring-net:
    driver: bridge

volumes:
  mongo-data:

