name: Orders Service CI/CD

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

env:
  SERVICE_NAME: orders
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: List target contents
        run: ls -l target

      - name: Prepare JAR for Docker
        run: |
          mkdir -p docker/target
          cp target/*.jar docker/target/orders.jar

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: orders-jar
          path: docker/target/orders.jar

  docker-build-push:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: orders-jar
          path: docker/target

      # ✅ Ajout pour que le cache fonctionne
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
